TABLE: 2_details
let
    Source = Excel.Workbook(File.Contents("C:\Users\Lenovo\Downloads\XXX\Dataset for Data Admin Case Study.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Invoice Date", type date}, {"Invoice #", type text}, {"Customer Name", type text}, {"Assigned Technicians", type text}, {"Created Date", type date}, {"Completion Date", type date}, {"Location Address", type text}, {"Location City", type text}, {"Location State", type text}, {"Location Zip", Int64.Type}, {"Job Type", type text}, {"Total", type number}}),
    #"5-digit zip clean" = Table.TransformColumns(#"Changed Type", {{"Location Zip", each Text.Start(Text.From(_, "en-US"), 5), type text}}),
    #"Sale Activity" = Table.AddColumn(#"5-digit zip clean", "Sale Activity", each if [Total] > 0 then "Yes" else "No"),
    #"Date Validation" = Table.AddColumn(#"Sale Activity", "Date Validation", each if [Completion Date] = null then "ongoing" else if [Completion Date] >= [Created Date] then "valid" else "date error"),
    #"Replace Null" = Table.ReplaceValue(#"Date Validation","",null,Replacer.ReplaceValue,{"Invoice Date", "Invoice #", "Customer Name", "Assigned Technicians", "Created Date", "Location Address", "Location City", "Location State", "Location Zip", "Job Type"}),
    #"Zip AB - LA replace" = Table.ReplaceValue(#"Replace Null","AB","LA",Replacer.ReplaceText,{"Location State"}),
    #"Filtered Rows" = Table.SelectRows(#"Zip AB - LA replace", each [Invoice Date] <> null and [Invoice Date] <> ""),
    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [#"Invoice #"] <> null and [#"Invoice #"] <> ""),
    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each [Customer Name] <> null and [Customer Name] <> ""),
    #"Filtered Rows3" = Table.SelectRows(#"Filtered Rows2", each [Assigned Technicians] <> null and [Assigned Technicians] <> ""),
    #"Filtered Rows4" = Table.SelectRows(#"Filtered Rows3", each [Created Date] <> null and [Created Date] <> ""),
    #"Filtered Rows5" = Table.SelectRows(#"Filtered Rows4", each [Location Address] <> null and [Location Address] <> ""),
    #"Filtered Rows6" = Table.SelectRows(#"Filtered Rows5", each [Location City] <> null and [Location City] <> ""),
    #"Filtered Rows7" = Table.SelectRows(#"Filtered Rows6", each [Location State] <> null and [Location State] <> ""),
    #"Filtered Rows8" = Table.SelectRows(#"Filtered Rows7", each [Location Zip] <> null and [Location Zip] <> ""),
    #"Filtered Rows9" = Table.SelectRows(#"Filtered Rows8", each [Job Type] <> null and [Job Type] <> ""),
    #"Loc Zip Clean" = Table.AddColumn(#"Filtered Rows9", "Location Zip Clean", each if Text.Length([Location Zip]) = 5 then [Location Zip] else null),
    #"Replaced Value" = Table.ReplaceValue(#"Loc Zip Clean","70063","70062",Replacer.ReplaceText,{"Location Zip Clean"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","70143","70037",Replacer.ReplaceText,{"Location Zip Clean"}),
    #"Filtered Rows10" = Table.SelectRows(#"Replaced Value1", each ([Location Zip Clean] <> null and [Location Zip Clean] <> "-7012")),
    #"Location Zip State to txt" = Table.TransformColumnTypes(#"Filtered Rows10",{{"Location Zip Clean", type text}}),
    #"Location Zip State" = Table.AddColumn(#"Location Zip State to txt", "Location Zip State", each [Location Zip Clean]&","&[Location State]),
    #"Removed Columns" = Table.RemoveColumns(#"Location Zip State",{"Column1", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19"}),
    #"job type group" = Table.AddColumn(#"Removed Columns", "Job Type Group", each let
    map = [
        #"Trim Out"="Installation/Construction",
        #"Installation/Changeout"="Installation/Construction",
        #"Rough In"="Installation/Construction",
        #"Misc"="Support/Admin",
        #"Quality Check for RNC or CNC"="Quality/Inspection",
        #"Warranty"="Service/Repair",
        #"New Construction"="Installation/Construction",
        #"2ND APP-2ND APPT SEE LAST TICKET"="Support/Admin",
        #"EST-W-Walk Thru"="Sales/Estimate",
        #"IN-FINS-Finish The INCOMPLETES"="Installation/Construction",
        #"C-202-NOT COOLING"="Service/Repair",
        #"INSPECT-Parish Inspection/or File"="Quality/Inspection",
        #"INS-FIN-Install Cond-grills VACUUME Ec"="Installation/Construction",
        #"Imported Default JobType"="Support/Admin",
        #"INS-CLE-Return For Clean Up"="Installation/Construction",
        #"INS-ROU-Install Inside Unit-ducts,ect."="Installation/Construction",
        #"777-Help Another Truck"="Support/Admin",
        #"INSTALL-CHANGE-l System See Estimate"="Sales/Estimate",
        #"Estimate/Sales"="Sales/Estimate",
        #"Residential Service"="Service/Repair",
        #"Quality Check for Change Outs"="Quality/Inspection",
        #"Heater Maintenance"="Maintenance/Agreement",
        #"AC Maintenance"="Maintenance/Agreement",
        #"Start Up"="Installation/Construction",
        #"COMPANY-Meeting-"="Support/Admin",
        #"Full System Maintenance"="Maintenance/Agreement",
        #"MA-SPR-Spring -1SYS / PD"="Maintenance/Agreement",
        #"C-009-Thermostat NOT ON"="Service/Repair",
        #"QUALITY-Quality Check Job"="Quality/Inspection",
        #"EST-Estimate- Meeting"="Sales/Estimate",
        #"MA-SP2-Spring - 2 System/ PD"="Maintenance/Agreement",
        #"MA SP2-RENEW 2-3 SPRING  /COLLECT"="Maintenance/Agreement",
        #"C-002-INSIDE Not Coming On"="Service/Repair",
        #"MA-NE2-New Maint/ Agree- 2 Syst"="Maintenance/Agreement",
        #"C-204-2 Visit For Dye Leak Detection"="Service/Repair",
        #"C-200-CALL BACK"="Service/Repair",
        #"C-060-Find Freon Leak"="Service/Repair",
        #"C-301-Move Condenser Unit"="Service/Repair",
        #"MA-FALL-Fall  1SYS- PD"="Maintenance/Agreement",
        #"H-100-No Heat"="Service/Repair",
        #"MA-COLL-PMA- Renewal -Collect"="Maintenance/Agreement",
        #"C-001-OUT SIDE Condenser Not Running"="Service/Repair",
        #"BALANCE-Balance Air /Hot And Cold Room"="Service/Repair",
        #"MA-F-2-Fall 2-3 SYSTEM/ PD"="Maintenance/Agreement",
        #"IN-DUCT-1 Drop"="Installation/Construction",
        #"MA-1-PD-Fall Ck.-pd"="Maintenance/Agreement",
        #"C-226-Replace-ordered Part"="Service/Repair",
        #"C-006-WATER LEAK"="Service/Repair",
        #"PICK-Pick Up Part"="Support/Admin",
        #"IN-STAR-Start Up 2 New System"="Installation/Construction",
        #"MA-NEW-New Maintance Agreement-1sys"="Maintenance/Agreement",
        #"C-302-Replace Outside Condenser"="Service/Repair",
        #"C-215-A/C Won't Shut Off"="Service/Repair",
        #"C-007-Repair Copper-Leak"="Service/Repair",
        #"C-222-Replace Evap.Coil- 2 Men"="Service/Repair",
        #"INS-STA-Start Up 1 New System"="Installation/Construction",
        #"IN/4-Set 2nd Cond. Vacuume"="Installation/Construction",
        #"IN-GRIL-Grills & Thermostat Only"="Installation/Construction",
        #"MA-SP-RENEWAL / SPRING/COLLECT"="Maintenance/Agreement",
        #"PARTORD-PICK UP PART ORDER"="Support/Admin",
        #"SALE-Act Of Sale Inspection"="Quality/Inspection",
        #"Recall on Installation"="Installation/Construction",
        #"Electrical"="Service/Repair",
        #"Commercial Service"="Service/Repair",
        #"Equipment Install"="Installation/Construction",
        #"700-Mantance Agrrement -cooling"="Maintenance/Agreement",
        #"C227-Replace TXV"="Service/Repair",
        #"305-Filter change"="Maintenance/Agreement",
        #"IN/3-Install Metal Duct System"="Installation/Construction",
        #"IN-FANC-Replace Vert Fancoil"="Installation/Construction",
        #"IN-COPP-Run New Copper Lines"="Installation/Construction",
        #"Generator Install"="Installation/Construction",
        #"IN/2-Install 4 Or More Flex Duct"="Installation/Construction",
        #"HELPER-2nd Man Needed For  Day"="Support/Admin",
        #"C-500-Noise From Unit"="Service/Repair",
        #"WINDO-CUSTOMER HAS WINDOW UNIT"="Invalid",
        #"C-125-Sees Mildew"="Service/Repair",
        #"C-203-Inject Dye"="Service/Repair",
        #"MS/REN-FALL/COLLECT  1 Sys RENEW"="Maintenance/Agreement",
        #"COMM-60-Install Commercial System"="Installation/Construction",
        #"C-008-Repair Drain Line"="Service/Repair",
        #"C-100-Replace Compressor"="Service/Repair",
        #"Set Condenser"="Installation/Construction",
        #"CHECK-PICK UP CHECK"="Support/Admin",
        #"PAPER W-Drop Off Paper Work"="Support/Admin",
        #"C-221-Replace Evap Coil -1 MAN"="Service/Repair",
        #"C-220-Unit FROZEN/  SHUT OFF UNIT"="Service/Repair",
        #"701-Maintance Agreement- Heater"="Maintenance/Agreement",
        #"H-001-Smells Smoke/ GAS"="Service/Repair",
        #"Full System Estimate"="Sales/Estimate",
        #"IN-FURN-Replace Horz. Frunace"="Installation/Construction",
        #"MA-SP 2-MA- Spring -2 Sys- Collect"="Maintenance/Agreement",
        #"GIL-WAR-Return Warranty Parts"="Support/Admin",
        #"Generator Service"="Service/Repair",
        #"INS-DEH-INSTALL DE HUMIDIFYER"="Installation/Construction",
        #"H-400-Replace Horizontal Furnace"="Service/Repair",
        #"C-223-Pull And Clean Cooling EV Coil"="Service/Repair",
        #"C-210-Compressor Short Cycles"="Service/Repair",
        #"C-225-Replac ORDERED Cond. Coil"="Service/Repair",
        #"INS-TES-Barometer Test"="Sales/Estimate",
        #"NO APPT-Do Not Sched This Time Block"="Invalid",
        #"VANS-Van Repairs Needed"="Support/Admin",
        #"VACATIO-VACATION"="Invalid",
        #"2TECK-SATURDAY ROTATION"="Support/Admin",
        #"ONCALL-PRIMARY"="Support/Admin",
        #"OFFICE-Office Work"="Support/Admin",
        #"TRIM-Repairs"="Installation/Construction",
        #"1ST-Go To 1st Call"="Support/Admin",
        #"COMM-10-Comm. Diagnostic"="Service/Repair",
        #"COMM-PM-Inspection PMA"="Maintenance/Agreement",
        #"DUCT-SEAL DUCT SYSTEM"="Service/Repair",
        #"H-325-Replace Gas Valve"="Service/Repair",
        #"REFRIGE-refrigeration- Repairs"="Service/Repair",
        #"C-010-Pull/Clean Blower[In Door]"="Service/Repair",
        #"AFTER H-AFTER HOURS 225.00"="Service/Repair",
        #"COMM--Site Meeting With Contractor"="Sales/Estimate"
    ]
in
    Record.FieldOrDefault(map, [Job Type], "Unclassified")),
    #"Trimmed Text" = Table.TransformColumns(#"job type group",{{"Customer Name", Text.Trim, type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Customer Name", Text.Clean, type text}}),

    #"Customer Name Grouped" = Table.AddColumn(#"Cleaned Text", "Customer Name Grouped", 
    each
        let
            name = Text.Upper(Text.Trim([Customer Name])),
            has = (words as list) as logical =>
                List.AnyTrue(List.Transform(words, (w) => Text.Contains(name, w))),
            segment =
                if has({"CHURCH","BAPTIST","LUTHERAN","EPISCOPAL","SCHOOL","MEDICAL","CLINIC","PARISH","GOVERNMENT","CENTER","HOSPITAL","PROVIDERS","PROJECT"}) then "Institutional"
                else if has({"PROPERTY","PROPERTIES","REALTY","APARTMENT","APARTMENTS","CONDO","ASSOCIATION","HOLDINGS","MANAGEMENT","DEVELOPMENT","LLC","RENTAL","COMMUNITY HOME"}) then "Property/Real Estate"
                else if has({"CONSTRUCTION","BUILDERS","BUILDER","HOMES","ROOF","HVAC","PLUMB","ELECTRIC","SUPPLY","CONTRACTOR","ENGINEERING","RESTORATION","RENOVATION"}) then "Builder/Trades"
                else if has({"CAFE","RESTAURANT","BBQ","GROCERY","SUBWAY","PIZZA","SUITES","HOTEL","INN","FITNESS","SALON","BAR","GRILL","STORE","MARKET"}) then "Retail/Hospitality"
                else if has({"BANK","INSURANCE","LAW","FIRM","CONSULTING","INVEST","TITLE","FINANCIAL"}) then "Professional/Finance"
                else if has({"&"," SR"," JR"}) or List.Count(List.Select(Text.Split(name, " "), each _ <> "")) <= 4 then "Residential"
                else "Unclassified"
        in
            segment,
    type text
),
    #"Renamed Columns" = Table.RenameColumns(#"Customer Name Grouped",{{"Job Type Group", "grouped_jobtype"}, {"Customer Name Grouped", "grouped_customersname"}, {"Location Zip State", "loc_zipstate"}, {"Location Zip Clean", "loc_zipclean"}, {"Date Validation", "check_datevalid"}, {"Sale Activity", "check_salesactivity"}, {"Total", "total"}, {"Job Type", "jobtype"}, {"Location Zip", "loc_zip"}, {"Location State", "loc_state"}, {"Location City", "loc_city"}, {"Location Address", "loc_add"}, {"Completion Date", "date_competion"}, {"Created Date", "date_create"}, {"Assigned Technicians", "assignedtech"}, {"Customer Name", "customername"}, {"Invoice #", "invoiceID"}, {"Invoice Date", "date_invoice"}}),
    #"Filtered Rows11" = Table.SelectRows(#"Renamed Columns", each ([check_datevalid] <> "date error") and ([grouped_jobtype] <> "Invalid") and ([grouped_customersname] <> "Unclassified")),
    #"Replaced Value2" = Table.ReplaceValue(#"Filtered Rows11",0.5,0,Replacer.ReplaceValue,{"total"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",0.01,0,Replacer.ReplaceValue,{"total"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","ongoing",null,Replacer.ReplaceValue,{"check_datevalid"}),
    #"Removed Blank Rows" = Table.SelectRows(#"Replaced Value4", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Removed Blank Rows1" = Table.SelectRows(#"Removed Blank Rows", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Filtered Rows12" = Table.SelectRows(#"Removed Blank Rows1", each ([check_datevalid] = "valid")),
    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows12",{"loc_add", "loc_city", "loc_state", "loc_zip", "assignedtech"}),
    #"Filtered Rows13" = Table.SelectRows(#"Removed Columns1", each ([loc_zipstate] <> "39503,MS" and [loc_zipstate] <> "39520,MS")),
    #"Renamed Columns1" = Table.RenameColumns(#"Filtered Rows13",{{"total", "rev"}})
in
    #"Renamed Columns1"